apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/knative-service.yaml
- manifests/doom/knative-service.yaml
images:
- name: IMAGE_FROM_KUSTOMIZATION
  newName: toska/toska-dev

